//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEW_EMPLOYEE
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Gender { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<System.DateTime> CreadtedOn { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string Hobbies { get; set; }
        public string PhotoPath { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
    
        public virtual tblDepartment tblDepartment { get; set; }
    }
}
